### ISSUE TITLE
Publish to Maven Central repository

### ISSUE THREAD

**Issue by ceefour** [ooxi/jdatauri#1]
would help a lot to Maven / Gradle users :)

**Comment by ooxi** [comment]
Thanks for your interest in jdatauri. I will publish to maven central repository shortly :)

**Comment by ooxi** [comment]
Just a heads up: I've created an [issue on OSSRH](https://issues.sonatype.org/browse/OSSRH-12458) which will lead to the publication of the jdatauri artifact in the maven central repository in one to two business days.

**Comment by ceefour** [comment]
Awesome :+1:

**Comment by ghost** [comment]
So far I cannot see any release or snapshot. Have you published any artifacts yet?

**Comment by ceefour** [comment]
Still hoping this will be done :)

**Comment by ooxi** [comment]
I have just published the artifact to Sonatype's release repository. As far as I understand the process, the sync has to be activated manually by Sonatype. I therefore have updated the OSSRH ticket and requested sync :)

**Comment by ceefour** [comment]
Super awesome :-)

**Comment by ooxi** [comment]
jDataUri is now published to [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cjdatauri) :)
