### ISSUE TITLE
Method to encode a Data URI (probably `toString()`)

### ISSUE THREAD

**Issue by ceefour** [ooxi/jdatauri#3]
Although encoding a data URI is trivial, it's be nice if this is convenience method of `DataURI` (probably `toString()`)

**Comment by ooxi** [comment]
This is so obvious, I wonder why I didn't already implement one o_O

Would you like to contribute a patch?

**Comment by slomkowski** [comment]
@ceefour, I've implemented it in pull request #4.

**Comment by ooxi** [comment]
Fixed by merging @slomkowski's implementation 3de03c555bacae2e0f84ad7f23bcd62d03da7ab2.
