### ISSUE TITLE
push 1.1 to maven repository

### ISSUE THREAD

**Issue by avodonosov** [ooxi/jdatauri#9]

**Comment by jayv** [comment]
What about deploying 1.2 to mvn central ?

**Comment by ccamel** [comment]
I would also be interested in having this one deployed to maven central. :smiley:

**Comment by ooxi** [comment]
I'm so sorry for not pushing all updates to maven central, it's a pia :-(

Would additional repositories like jfrog be of any use to you?

**Comment by avodonosov** [comment]
What is pia? Looking in google, but can't find a suitable explanation.

**Comment by ooxi** [comment]
> What is pia? Looking in google, but can't find a suitable explanation.

pain in the _advertiser friendly content_ ;-)

**Comment by avodonosov** [comment]
I'm starting to understand the abbreviation.

But why you dont push to maven central? Do yoy dislike it personally and have a principle, or it's something else?

**Comment by ccamel** [comment]
@ooxi
To me, any kind of repositories would be fine (we use a repository manager). :+1:

**Comment by ooxi** [comment]
While I did not manage to publish 1.1, I finally managed to publish [1.2](https://search.maven.org/artifact/com.github.ooxi/jdatauri/1.2/jar) to Maven Central 🎉

@ccamel I have not tried it but using [JitPack](https://jitpack.io/#ooxi/jdatauri/) seems promising. It publishes GitHub repositories as Maven Repositories without needing author interaction.

Feel free to reopen this issue or create another one if you have trouble consuming the published artifact.

**Comment by ccamel** [comment]
Thanks @ooxi. It worked perfectly. :relieved: 

Yes `JitPack` is amazing and works really well. After declaring the `jitpack.io` repository in our Repository Manager (i.e. Nexus), for testing, I managed to download the following dependency with maven:

```xml
<dependency>
    <groupId>com.github.ooxi</groupId>
    <artifactId>jdatauri</artifactId>
    <version>feature~20161231-multiple-jdk</version>
</dependency>
```
